### ISSUE TITLE
What is Salt - very vague, not sure what the site is for

### ISSUE THREAD

**Issue by mldenne** [ifasoldt/Salt#28]
Even after reading everything on the page, I'm still not sure what the site is for. Use Airbnb as an example. On the landing page it states plainly: Book homes from local hosts and experience a place like you live there.
Bam - like magic, I know what the site is about. All you need is one sentence...here's an idea:
Like to cook? Like to host events? Like to meet new people?
- or -
  Home cooked meals that are an event everyone wants to attend.

**Comment by jwillingham789** [comment]
done and done
